### ISSUE TITLE
Complex boundary checks

### ISSUE THREAD

**Issue by kostya9** [olevchuck/EuroDiffusion#10]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.cpp#L67

Maybe let's introduce a `between(value, min, max)` function because currently it is hard to read this set of checks. I would also recommend to introduce two separate variables: one for boundary checks and another for checks that left is greater than right

**Comment by olevchuck** [comment]
Done
