### ISSUE TITLE
Method naming for checks

### ISSUE THREAD

**Issue by kostya9** [olevchuck/EuroDiffusion#11]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.h#L21

I would recommend to name methods that return a boolean in the following manner: `Is...()`, `Are...()` (e.g. `AreCountriesColliding()`, `IsNeighborValid()`). The meaning of the `Check...()` methods are not straightforward because the check could indicate anything, and it would be helpful to know what exactly is the method checking for.

I think that `Validate...()` kind of methods could also be renamed to the same model (`Is...()`, `Are...()`) https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.h#L15
I would expect a `Validate...()` method to throw an exception because the name tells me that the return type is highly probable to be `void`

**Comment by olevchuck** [comment]
Done
