### ISSUE TITLE
Coordinate translation

### ISSUE THREAD

**Issue by kostya9** [olevchuck/EuroDiffusion#15]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.cpp#L18

Can we consider to introduce a method for the coordinate translation from 2d to 1d? Something like `GetCityAtPosition(x, y)`

**Comment by olevchuck** [comment]
Done, implemented GetCityHash() method
