### ISSUE TITLE
Auto keyword for lambdas

### ISSUE THREAD

**Issue by kostya9** [olevchuck/EuroDiffusion#16]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.cpp#L81

Can we use `auto` keyword for lambda and lambda parameters type? This can remove the need of the typedef

**Comment by kostya9** [comment]
AFAIK c++14 added auto support for lambda params https://isocpp.org/wiki/faq/cpp14-language#generic-lambdas

**Comment by olevchuck** [comment]
If you don`t mind, I`ll leave it as it is just for readability
