### ISSUE TITLE
Use const ref

### ISSUE THREAD

**Issue by IanaKhitsko** [olevchuck/EuroDiffusion#3]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/Country.h#L7

use const ref for the parameter.

**Comment by olevchuck** [comment]
Done

**Comment by IanaKhitsko** [comment]
Please note, that you shall use const ref for strings only in case of  parameter in method. Do not use const string& as struct member (as you did after issue fix), you can't guarantee that memory will not be corrupted.
