### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by IanaKhitsko** [olevchuck/EuroDiffusion#5]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.cpp#L56

you create City in this class and most probably clean up in another place. This is unsafe. Please either clean up them here or use smart pointers

**Comment by olevchuck** [comment]
I`ve implemented a FreeMemory method for readability (I think that usage of smart pointers is an overcomplicated solution for this problem because this program is single-threaded)
