### ISSUE TITLE
Remove consts from the class

### ISSUE THREAD

**Issue by IanaKhitsko** [olevchuck/EuroDiffusion#9]
https://github.com/olevchuck/EuroDiffusion/blob/a2a6523d983292fb5cc7b6ccbabebe2757a4e1cc/EuroDiffusionManager.h#L38-L39

Please remove these from the class, you can just define out of the class

**Comment by olevchuck** [comment]
But why? I`m using these constants not only in one place ( methods for checking/finding neighbours and input validation)

**Comment by olevchuck** [comment]
Fixed
